name: Build and test

on:
  push:
    branches: [ main, build-debug-image ]
  pull_request:
    branches: [ main ]

jobs:
  php:
    runs-on: ubuntu-latest
    name: "Build and test"
    strategy:
      matrix:
        php: ['8.0', '8.1'] #, '8.2']
    container:
      image: ghcr.io/brettmc/opentelemetry-php-instrumentation/php:${{ matrix.php }}-debug

    steps:
      -   uses: actions/checkout@v2

      -   name: Build
          run: |
            phpize
            ./configure
            make

      -   name: Test
          run: make test
